# Generated by Django 2.2.12 on 2020-04-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0001_initial'),
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('oIsPay', models.BooleanField(default=False)),
                ('oDate', models.DateTimeField(auto_now=True)),
                ('oAdress', models.CharField(max_length=150)),
                ('oTotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('oUser', models.ForeignKey(on_delete=None, to='df_user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goods', models.ForeignKey(on_delete=None, to='df_goods.GoodsInfo')),
                ('order', models.ForeignKey(on_delete=None, to='df_order.OrderInfo')),
            ],
        ),
    ]
