# Generated by Django 2.2.12 on 2020-04-21 16:50

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(db_column='标题', max_length=20, verbose_name='类型名称')),
                ('isDelete', models.BooleanField(db_column='是否删除', default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '分类信息',
                'verbose_name_plural': '分类信息',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(db_column='标题', max_length=20, verbose_name='商品名称')),
                ('gpic', models.ImageField(db_column='图片位置', upload_to='media', verbose_name='商品图片')),
                ('gprice', models.DecimalField(db_column='价格', decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('gunit', models.CharField(db_column='单位', default='500g', max_length=20, verbose_name='商品单位')),
                ('gclick', models.IntegerField(db_column='点击数量', verbose_name='点击量')),
                ('isDelete', models.BooleanField(db_column='是否删除', default=False, verbose_name='是否删除')),
                ('gjianjie', tinymce.models.HTMLField(db_column='简介', verbose_name='简介')),
                ('gkucun', models.IntegerField(db_column='库存', verbose_name='库存')),
                ('gcontent', tinymce.models.HTMLField(db_column='详细情况', verbose_name='详细介绍')),
                ('gtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.TypeInfo', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
    ]
